apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-intelligence
  namespace: gie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-intelligence
  template:
    metadata:
      labels:
        app: recommendation-intelligence
    spec:
      containers:
        - name: api
          image: gie/recommendation-intelligence:1.0.0
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-intelligence
  namespace: gie
spec:
  selector:
    app: recommendation-intelligence
  ports:
    - port: 8085
      targetPort: 8085
