from __future__ import annotations
from typing import Any, Protocol
from uuid import UUID
from gie_contracts.orchestrator import ExecutionRecord, ExecutionTrace


class ExecutionRepository(Protocol):
    async def save(self, record: ExecutionRecord) -> None: ...
    async def get(self, execution_id: UUID) -> ExecutionRecord | None: ...
    async def list(
        self, tenant_id: str, limit: int = 50, offset: int = 0
    ) -> list[ExecutionRecord]: ...
    async def count_active(self) -> int: ...


class TraceRepository(Protocol):
    async def save(self, trace: ExecutionTrace) -> None: ...
    async def get(self, trace_id: str) -> ExecutionTrace | None: ...


class CacheStore(Protocol):
    async def get_json(self, key: str) -> dict[str, Any] | None: ...
    async def set_json(self, key: str, value: dict[str, Any], ttl: int) -> None: ...
    async def size(self) -> int: ...


class EventPublisher(Protocol):
    async def publish(
        self, topic: str, event: dict[str, Any], key: str | None = None
    ) -> None: ...


class AgentInvoker(Protocol):
    async def invoke(
        self, agent_id: str, version: str, payload: dict[str, Any], *, timeout_ms: int
    ) -> dict[str, Any]: ...
    async def health(self) -> list[dict[str, Any]]: ...
