apiVersion: v1
kind: Service
metadata:
  name: policy-generator
  labels:
    app: policy-generator
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: policy-generator
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
