from __future__ import annotations
from typing import Any, Protocol
from uuid import UUID
from gie_contracts.integration import (
    AuditLogEntry,
    IntegrationConnection,
    SyncResult,
    WebhookEvent,
)

class ConnectionRepository(Protocol):
    async def save(self, conn: IntegrationConnection) -> None: ...
    async def get(self, connection_id: UUID) -> IntegrationConnection | None: ...
    async def list(self, tenant_id: str, limit: int = 100, offset: int = 0) -> list[IntegrationConnection]: ...

class WebhookRepository(Protocol):
    async def save(self, event: WebhookEvent) -> None: ...
    async def list(self, tenant_id: str, limit: int = 100, offset: int = 0) -> list[WebhookEvent]: ...

class AuditRepository(Protocol):
    async def save(self, entry: AuditLogEntry) -> None: ...
    async def list(self, tenant_id: str, limit: int = 100, offset: int = 0) -> list[AuditLogEntry]: ...

class SyncRepository(Protocol):
    async def save(self, result: SyncResult) -> None: ...
    async def list(self, tenant_id: str, limit: int = 50, offset: int = 0) -> list[SyncResult]: ...

class SecretStore(Protocol):
    async def put(self, key: str, value: dict[str, Any]) -> None: ...
    async def get(self, key: str) -> dict[str, Any] | None: ...
    async def delete(self, key: str) -> None: ...

class EventPublisher(Protocol):
    async def publish(self, topic: str, event: dict[str, Any], key: str | None = None) -> None: ...

class CacheStore(Protocol):
    async def get_json(self, key: str) -> dict[str, Any] | None: ...
    async def set_json(self, key: str, value: dict[str, Any], ttl: int) -> None: ...
